source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'haml-rails', '~> 0.9'
gem 'cocoon'
gem 'jquery-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails', '~> 4.4.1'
  gem 'pry-rails'
  gem 'pry'
  gem 'pry-nav'
end
